package diamondEngine.diaEvents;

public enum DiaEventType {
    DEFAULT,
    ASSET_ADDED,
    ASSET_REMOVED,
    CURRENT_ENVIRONMENT_SWITCHED,
    MOUSE_INPUT,
    KEYBOARD_INPUT,
    ENTITY_ADDED,
    ENTITY_REMOVED,
    HIERARCHY_UPDATED
}
