package sapphire.eventsSystem;

public enum SappEventType {
    User_event,
    Settings_changed,
    Font_changed,
    Play,
    Stop,
    Confirm,
    Cancel,
    Add_env,
    Add_entity,
    Add_component,
    Selected_object,
    Save_env,
    New_root_env,
    Change_font,
    New_file,
    Open_file,
    Save_file,
    Save_as,
    Create_project,
    Open_project,
    Export_project,
    Settings,
    Delete_object,
    Delete_file,
    Import_env,
    Save_env_as,
    Add_asset
}
